#!/bin/bash

printf "New File Name:\t"
read file_name
touch $file_name
echo -e "#include <stdio.h>

/**
 * main - entry point
 *
 * Return: Always 0.
 */
int main(void)
{
        printf("with proper grammar, but the outcome is a piece of art,\n");
        return (0);
}" > $file_name
chmod u+x $file_name
vi $file_name
