#!/bin/bash

printf "New File Name:\t"
read file_name
touch $file_name
echo -e "#include \"main.h\"
#include <unistd.h>
/**
 * main - CHECK YOUR PROTOTYPE
 *
 * Return: CHECK YOUR PROTOTYPE
 */
int main(void) CHECK YOUR PROTOTYPE
{
	char c[] = \"YOURTEXTHERE\";
	int x;

	for (x = 0; x < ###; x++)
	{
		_putchar(c[x]);
	}
	_putchar('\\n');

	return (0);
}" > $file_name
chmod u+x $file_name
vi $file_name
